snap/pack: disallow packing snapd, os and base snaps with default-/configure hooks
canonical/snapd pull request #13117
Opened 2023-08-24 13:48 UTC by ernestl

This PR builds on https://github.com/snapcore/snapd/pull/13097.

Implements draft [spec](https://docs.google.com/document/d/1qQsxCrhlCKUb33_1mdY88sRHeFZStFnydh7mirA3S0Y/edit?usp=drive_link) part: Prohibit user-defined configuration hooks for specific essential snaps

Outstanding: testing and unit tests

2025-01-28 09:42 UTC, miguelpires approved these changes
lgtm

2025-01-30 14:37 UTC, ZeyadYasser approved these changes
LGTM

2025-02-03 16:51 UTC, pedronis requested changes
some comments

2025-02-03 16:51 UTC, pedronis commented on overlord/snapstate/check_snap.go
> -func checkConfigureHooks(_ *state.State, snapInfo, curInfo *snap.Info, _ snap.Container, _ Flags, deviceCtx DeviceContext) error {
we probably want to keep this as well

2025-02-03 16:51 UTC, pedronis commented on snap/validate.go
> +	if info.SnapType == TypeSnapd || info.SnapType == TypeBase || (info.SnapType == TypeOS && info.InstanceName() != "core") {
only "core" and "ubuntu-core" exist with TypeOS both could have have a configure hook, so I don't think it's worth checking for the name, same above

2025-02-05 11:28 UTC, ernestl commented on overlord/snapstate/check_snap.go
> -func checkConfigureHooks(_ *state.State, snapInfo, curInfo *snap.Info, _ snap.Container, _ Flags, deviceCtx DeviceContext) error {
I put this back.

I checked, and I am not aware of a path where CheckSnap() validates without snap/validate.go validation also happening. I have not included the snap type based checks here.

2025-02-05 11:31 UTC, ernestl commented on snap/validate.go
> +	if info.SnapType == TypeSnapd || info.SnapType == TypeBase || (info.SnapType == TypeOS && info.InstanceName() != "core") {
Allowed all OS snaps to have configure hooks.

`core` snap has empty configure hook, however did not see this for most recent version of `ubuntu-core`, at least not implicit.

2025-02-13 09:38 UTC, pedronis requested changes
thanks for the changes, something seems a bit off with the error message building logic though, otoh made a different suggestion

2025-02-13 09:38 UTC, pedronis commented on snap/validate.go
>  			if hasConfigureHook {
this now needs to become the same check as below, no? but then I'm unsure using a strings.Builder is the best approach, wouldn't a  []string and using Join with " or " be simpler?

2025-02-13 20:46 UTC, ernestl commented on snap/validate.go
>  			if hasConfigureHook {
thanks, corrected and simplified this and corresponding test

2025-02-14 16:29 UTC, pedronis approved these changes
thank you, @ernestl this has changed a bit since. maybe you can get one of the original reviewers to do a quick 2nd pass?

2025-02-17 15:42 UTC, miguelpires reviewed
Looks good, just some comments on testing

2025-02-17 15:42 UTC, miguelpires commented on snap/pack/pack_test.go
> +		}
We can simplify this
```suggestion
		c.Assert(os.Mkdir(filepath.Join(sourceDir, "meta", "hooks"), 0755), IsNil)
		c.Assert(os.WriteFile(filepath.Join(sourceDir, "meta", "hooks", "configure"), []byte("#!/bin/sh"), 0755), IsNil)
```

2025-02-17 15:42 UTC, miguelpires commented on snap/pack/pack_test.go
> +		}
The `configure` case is already covered in the test above, so we can remove it from this one
```suggestion
		c.Assert(os.Mkdir(filepath.Join(sourceDir, "meta", "hooks"), 0755), IsNil)
		c.Assert(os.WriteFile(filepath.Join(sourceDir, "meta", "hooks", "default-configure"), []byte("#!/bin/sh"), 0755), IsNil)
```

2025-02-17 15:42 UTC, miguelpires commented on snap/pack/pack_test.go
> +		}
```suggestion
		c.Assert(os.Mkdir(filepath.Join(sourceDir, "meta", "hooks"), 0755), IsNil)
		c.Assert(os.WriteFile(filepath.Join(sourceDir, "meta", "hooks", "configure"), []byte("#!/bin/sh"), 0755), IsNil)
```

2025-02-17 15:42 UTC, miguelpires commented on snap/pack/pack_test.go
> +		}
```suggestion
		c.Assert(os.Mkdir(filepath.Join(sourceDir, "meta", "hooks"), 0755), IsNil)
		c.Assert(os.WriteFile(filepath.Join(sourceDir, "meta", "hooks", "default-configure"), []byte("#!/bin/sh"), 0755), IsNil)
```

2025-02-17 15:42 UTC, miguelpires commented on snap/pack/pack_test.go
These tests are really similar and could be refactored into a single table test that maps a snapType/hookType combinations to the error message:
```
type testcase struct {
  snapType string
  hookErr     map[string]string
}
...
{
  snapType: "os",
  hookErr: map[string]string{"configure": "", "default-configure": "cannot specify ..."
}
```
Then the test would do what it already does, pack the snap of snapType with the hook and check the map to see what it should expect (hookErr would be "" if it should be allowed or an error message, if not).

But maybe the effort of rewriting them now isn't really worth it, so I'm good with keeping this as it is

2025-02-19 12:04 UTC, ernestl commented on snap/pack/pack_test.go
> +		}
`default-configure` hook always requires `configure` hook, otherwise you get an error as per `TestPackDefaultConfigureWithoutConfigureError`

Let me add a note.

2025-02-19 12:09 UTC, miguelpires commented on snap/pack/pack_test.go
> +		}
Ah of course, my mistake

2025-02-19 12:10 UTC, miguelpires approved these changes
looks good, thanks for the clarification

2025-02-19 12:28 UTC, ernestl commented on snap/pack/pack_test.go
> +		}
default-configure hook always requires configure hook, otherwise you get an error as per TestPackDefaultConfigureWithoutConfigureError

Will change name to TestPackKernelGadgetAppWithDefaultConfigureAndConfigureHookHappy

2025-02-19 12:29 UTC, ernestl commented on snap/pack/pack_test.go
> +		}
thanks, improved

2025-02-19 12:29 UTC, ernestl commented on snap/pack/pack_test.go
> +		}
thanks, improved

2025-02-19 12:29 UTC, ernestl commented on snap/pack/pack_test.go
> +		}
thanks, improved

2025-02-20 10:35 UTC, merged