spread.yaml: switch to using ubuntu-image from latest/edge
canonical/snapd pull request #13317
Opened 2023-10-20 08:41 UTC by alfonsosanchezbeato

Now ubuntu-image is statically compiled so the issues with libc should be gone. Also, it has been detected that 2/stable creates partitions with unsupported features in older systems as it is shipping mkfs.ext4 in the snap, which comes from 20.04, but the one in latest is not shipping it.

2023-10-20 11:23 UTC, sergiocazzolato approved these changes
Perfect, thanks for updating this.

2023-10-20 12:42 UTC, sergiocazzolato commented
I see ubuntu-image failing to prepare in uc16

+ /snap/bin/ubuntu-image snap -w /home/image /home/image/pc.model --channel edge --snap /home/gopath/src/github.com/snapcore/snapd/tests/main/lxd/pc-kernel_1429.snap --snap /home/image/core_16-2.61+git4836.3d70bf83a_amd64.snap --output-dir /home/image
[0] make_temporary_directories
[1] determine_output_directory
[2] prepare_image
WARNING: proceeding to download snaps ignoring validations, this default will change in the future. For now use --validation=enforce for validations to be taken into account, pass instead --validation=ignore to preserve current behavior going forward
WARNING: "core" installed from local snaps disconnected from a store cannot be refreshed subsequently!
[3] load_gadget_yaml
WARNING: volumes:pc:structure:2:filesystem_label used for defining partition roles; use role instead
[4] set_artifact_names
[5] populate_rootfs_contents
[6] generate_disk_info
[7] calculate_rootfs_size
[8] populate_bootfs_contents
[9] populate_prepare_partitions
Error: Error running mkfs with content: 
-----
mkfs.ext4: invalid option -- 'd'
Usage: mkfs.ext4 [-c|-l filename] [-b block-size] [-C cluster-size]
	[-i bytes-per-inode] [-I inode-size] [-J journal-options]
	[-G flex-group-size] [-N number-of-inodes]
	[-m reserved-blocks-percentage] [-o creator-os]
	[-g blocks-per-group] [-L volume-label] [-M last-mounted-directory]
	[-O feature[,...]] [-r fs-revision] [-E extended-option[,...]]
	[-t fs-type] [-T usage-type ] [-U UUID] [-jnqvDFKSV] device [blocks-count]

2023-10-20 16:50 UTC, sergiocazzolato requested changes
I see this error:
mkfs.ext4: invalid option -- 'd'

When running with channel 2/stable the image is created correctly

2023-10-23 07:41 UTC, ZeyadYasser commented
> I see ubuntu-image failing to prepare in uc16
>
>    /snap/bin/ubuntu-image snap -w /home/image /home/image/pc.model --channel edge --snap /home/gopath /src/github.com/snapcore/snapd/tests/main/lxd/pc-kernel_1429.snap --snap /home/image/core_16-2.61+git4836.3d70bf83a_amd64.snap --output-dir /home/image
>    [0] make_temporary_directories
>    [1] determine_output_directory

@sergiocazzolato @alfonsosanchezbeato it looks like this caused by a pending todo in snapd https://github.com/snapcore/snapd/blob/e5cfcd50300a33d0b3b3303f9948727d8f60a72c/osutil/mkfs/mkfs.go#L98-L103

I think we could either patch this in snapd (but do we want to still support uc16??) or just set `UBUNTU_IMAGE_SNAP_CHANNEL` to `2/stable` for uc16 tests.

2023-10-23 07:44 UTC, ZeyadYasser reviewed
> I see ubuntu-image failing to prepare in uc16
>
>    /snap/bin/ubuntu-image snap -w /home/image /home/image/pc.model --channel edge --snap /home/gopath /src/github.com/snapcore/snapd/tests/main/lxd/pc-kernel_1429.snap --snap /home/image/core_16-2.61+git4836.3d70bf83a_amd64.snap --output-dir /home/image
>    [0] make_temporary_directories
>    [1] determine_output_directory

@sergiocazzolato @alfonsosanchezbeato it looks like this caused by a pending todo in snapd https://github.com/snapcore/snapd/blob/e5cfcd50300a33d0b3b3303f9948727d8f60a72c/osutil/mkfs/mkfs.go#L98-L103

I think we could either patch this in snapd (but do we want to still support uc16??) or just set `UBUNTU_IMAGE_SNAP_CHANNEL` to `2/stable` for uc16 tests.

2023-10-23 07:48 UTC, alfonsosanchezbeato commented
Thanks for the reviews - I'm converting this to draft. I wonder if maybe we should move forward with using track `2` for UC16 and `latest` for the rest.

2023-10-23 07:49 UTC, ZeyadYasser commented
> Thanks for the reviews - I'm converting this to draft. I wonder if maybe we should move forward with using track `2` for UC16 and `latest` for the rest.

+1 on this approach.

2024-01-10 14:41 UTC, alfonsosanchezbeato commented
TODO: retry once https://github.com/canonical/ubuntu-image/pull/170 is merged

2024-11-22 15:22 UTC, closed without merging