tests: spread metadata used to filter and categorize tests
canonical/snapd pull request #13971
Opened 2024-05-16 09:38 UTC by sergiocazzolato

This change introduces metadata on spread tests, this metadata is divided in features, groups and tags.

In all cases the metadata can be used to filter tests to be executed in different circunstancies, but also to know test coverage.

The file spread.meta.yaml includes the values allowed to include in the tests. These values will be cross-checked in the ci to check the tests integrity.

The tests updated are just done as an example in order to understand how tests are going to looks like.

2024-05-27 21:55 UTC, ernestl reviewed
Thanks, this looks like a really useful capability. 
Some comments.
Furthermore: 
- It might be useful to explain the envisioned rules of use e.g. can I filter by feature within a group?, filter by multiple features/groups etc.
- Do we perhaps need to cater for sub-features/granularity. If so, how to simplify this, do we perhaps want to consider a path-like notation?

2024-05-27 21:55 UTC, ernestl commented on spread.meta.yaml
> +    # Groups are set of tests orthogonal to the suites definition
Perhaps we can explain "orthogonal" in more practical terms e.g. set of tests that can be selected across multiple suites? 

Assuming that's what is meant, is this not true to tags and features as well?

2024-05-27 21:55 UTC, ernestl commented on spread.meta.yaml
> +    # Tags are free labels used to identify group of tests
Wondering if the concept of tags is not similar enough to group that is not required as a separate concept?

2024-05-28 08:52 UTC, pedronis requested changes
as I also discussed with @ernestl I think we need to have a mini specs to discuss what the different tag kinds are for, and naming conventions, initial listing for each of them

2024-07-15 12:59 UTC, zyga requested changes
I think this needs an update based on the spec changes I've seen.

2025-02-21 20:42 UTC, closed without merging