o/snapstate: remove unused slice that is only appended to
canonical/snapd pull request #13972
Opened 2024-05-16 11:54 UTC by andrewphelpsj

Removes an unused slice, unsure what it was originally used for.

2024-05-16 11:57 UTC, andrewphelpsj commented
Actually, after reading this undo handler more carefully, does it even do anything?

2024-05-16 12:29 UTC, MiguelPires reviewed
I see:
```
	// TODO: telemetry about errors here
```
at the end of the handler so I'm guessing this was meant to collect information about the error to eventually do something with it? But it was added in 2017 so the plan might've changed. Maybe @pedronis remembers

2024-05-21 14:20 UTC, bboozzoo commented on overlord/snapstate/handlers.go
>  	dupSig := []string{"snap-install:"}
dupSig appears to be equally useless?

2024-05-29 14:57 UTC, pedronis requested changes
in theory we can empty the whole definition and just leave the TODO about telemetry for errors, a different approach would be to replace the code with a short text that list what we were/would want to capture

at some past point this code was sending the computed info to the errortracker but we removed this because that's wasn't working/scaling for us (afair)

2024-08-19 06:43 UTC, Meulengracht commented
@andrewphelpsj would you mind updating the status of this PR?

2024-08-19 20:36 UTC, andrewphelpsj commented
@Meulengracht I took @pedronis' suggestion and just removed the handler with a TODO about telemetry for now.

2024-08-20 06:45 UTC, bboozzoo approved these changes
Thank you

2024-08-20 08:24 UTC, MiguelPires approved these changes
lgtm

2024-08-22 14:51 UTC, pedronis approved these changes
+1

2024-08-23 11:40 UTC, merged