seedwriter: check if the optionSnap channel is same as model assert
canonical/snapd pull request #14071
Opened 2024-06-12 08:44 UTC by AristoChen

If we define `presence: optional` for an app snap in model assertion, and the default channel is `24/stable` for example, then when we pass `--snap=SNAP=24/stable` to `snap prepare-image` with a model assertion that has model grade higher than dangerous, I will get an error `error: cannot override channels, add devmode snaps, local snaps, or extra snaps with a model of grade higher than dangerous`

However, I am expecting that snapd should check whether the channel for option snap is same as the channel defined in model assertion, maybe snapd should only return error if channel is not the same and the model grade is higher than dangerous

2024-06-28 11:31 UTC, bboozzoo requested changes

2024-06-28 11:31 UTC, bboozzoo commented on seed/seedwriter/writer.go
> -			if err := w.policy.checkSnapChannel(ch, whichSnap); err != nil {
AFAIU the original check is intentional and if you are using a mode with grade > dangerous, the channel is already specified in the model itself, thus it is a mistake to attempt to pass one in the command line.

Note that it is enough to pass the snap name as `--snap <name>` to include an optional snap. During seeding the snap will be set up to track the right channel

2024-07-01 11:56 UTC, pedronis reviewed
The current behavior is mostly so that the check is very simple and consistent, and there is no giving the impression that one can specify a different channel if grade != dangerous. What's the use case for passing in a channel anyway? As @bboozzoo explained `--snap <name>` is enough to trigger inclusion of the optional snap.

2024-07-03 09:54 UTC, AristoChen commented
Thanks for the explanation!

Previously I wasn't familiar with the `presence: optional`, so I tried `--snap=SNAP_NAME=CHANNEL` to see if it the snap can be included in the image, but the error message(`error: cannot override channels, add devmode snaps, local snaps, or extra snaps with a model of grade higher than dangerous`) is confusing because I am not overriding the channels.

IMO, maybe snapd should accept both `--snap=SNAP_NAME=CHANNEL` and `--snap SNAP_NAME` if `presence` is set to optional, or at least snapd should print a more meaningful message to let user know `--snap SNAP_NAME` should be used instead of `--snap=SNAP_NAME=CHANNEL`

I just realized that my original patch will affect all scenarios even if `presence` is not set to `optional`, so I just force pushed a new commit to make it more restrict and only works for `presence: optional`

2024-12-13 12:47 UTC, pedronis commented
I opened https://github.com/canonical/snapd/pull/14856 to improve the error message, mentioning that `--snap=<snap-name>` is still allowed

2024-12-17 09:30 UTC, closed without merging