interfaces/udisks2: Make it available on Core
canonical/snapd pull request #14334
Opened 2024-08-08 17:25 UTC by er-vin

Otherwise processes can't talk to it even if provided by the base snap and started.

2024-08-09 01:26 UTC, alexmurray requested changes
Traditionally this interface has been provided by the udisks2 snap on Ubuntu Core IIRC - so unless something has changed and udisks2 is now provided by the various base snaps in Ubuntu Core, this can't just be made ImplicitOnCore - instead you should use `implicitOnCore: release.OnCoreDesktop` I think - see https://github.com/canonical/snapd/blob/ea13a335211bd7e249cc353df75db0524c4edc0b/interfaces/builtin/steam_support.go#L406-L409 and the discussion in https://github.com/canonical/snapd/pull/14109 for details.

2024-08-12 09:19 UTC, jhenstridge commented
Based on the design discussions over the last few weeks, we want to move to using a udisks2 snap rather than including it in the boot base snap + an implicit slot. I think the same would go for the KDE variant.

While the [currently published version](https://snapcraft.io/udisks2) is ancient, I know @valentindavid had started work on an update:

https://github.com/snapcore/udisks2-snap

Still, it looks like nothing has published since 2017. I'm not sure if this is down to waiting on credentials, or whether there is a release stuck in manual review.

2024-08-14 10:14 UTC, er-vin commented
I got no problem abandoning this PR once we got a new udisks2 snap available of course. Any ETA from @valentindavid ?

2024-09-03 08:07 UTC, valentindavid commented
> I got no problem abandoning this PR once we got a new udisks2 snap available of course. Any ETA from @valentindavid ?

The request for 22 branch is in https://forum.snapcraft.io/t/manual-review-for-udisks2-part-2/40923

Once we have it for 22, we will add 24.

2024-09-06 08:07 UTC, ernestl commented
May I reject this given the progress on https://forum.snapcraft.io/t/manual-review-for-udisks2-part-2/40923/7?

@valentindavid

2024-09-13 08:15 UTC, closed without merging

2024-09-13 08:15 UTC, ernestl commented
Agreement to reject this PR.