many: rename registry role s/manager/custodian
canonical/snapd pull request #14487
Opened 2024-09-11 16:23 UTC by MiguelPires

The manager role has been renamed to custodian to reflect that the snap is responsible for the registry data but any snap can modify it (assuming it plugs a view that allows it).

2024-09-12 07:54 UTC, ZeyadYasser requested changes
I did a quick first pass, I think `getManagerPlugsForView` under `overlord/registerystate` needs to be updated as well.

2024-09-12 08:44 UTC, MiguelPires commented
Thanks @ZeyadYasser for the review, I've update that function (as tests) as well

2024-09-12 12:04 UTC, ZeyadYasser approved these changes
LGTM

2024-09-13 14:48 UTC, olivercalder approved these changes
Looks good to me, thanks!

2024-09-13 16:01 UTC, merged